## Calibration Analysis Script for 6th June 2023 Shot Day.
## This script provides the instrument calibration and FWHM information 
## for the IAW and EPW diagnostics.
## Generated by: H. Poole

#%%
## Import necessary libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import peakutils
import sys
import scipy.constants as cst
from pyhdf.SD import SD, SDC
from scipy.optimize import curve_fit
#%%

#%%
## Import data
###############################################################
##                                                           ##
##                        DATA TO INPUT                      ##
##                                                           ##
###############################################################

## Define the shot day, shot number, and diagnostic
Shot_day = 'OMEGA_Jun2023'
Shot_number = 0
Diagnostic = 'IAW'
## If using TDYNO_NLUF Box account, User as required in Parent_loc
User = 'hpoole'

###############################################################

###############################################################
##                                                           ##
##                      FILE LOCATIONS                       ##
##                                                           ##
###############################################################

Parent_loc = os.path.join('/', 'Users', User, 'Library', 'CloudStorage', 'Box-Box', 'TDYNO_NLUF', 'OMEGA', Shot_day, 'Data', f'{Shot_number}', Diagnostic)

if Diagnostic == 'IAW':
    File_loc = os.path.join(Parent_loc, 'IAW_532_1o_532cw_500um_121p71_270.hdf')
elif Diagnostic == 'EPW':
    ## The EPW has two calibration files (due to error on the day)
    ## This file provides the FWHM
    File_loc = os.path.join(Parent_loc, 'EPW_FWHM_100um_263p5cw_ross_150ph.hdf')
    ## This file provides the alignment calibration
    # file_loc = os.path.join(parent_loc, 'EPW_align_532_1o_527cw_500um_121p71_270.hdf')

## Check if the file exists
if not os.path.exists(File_loc):
    print(f"File not found: {File_loc}")
    sys.exit(1)
###############################################################


# %%
