## Calibration Analysis Script for OMEGA Optical Thomson Scattering
## This script provides the instrument calibration and FWHM information 
## for the IAW and EPW diagnostics.
## Generated by: H. Poole

## Import necessary libraries
import os
from tkinter import Image
import numpy as np
import matplotlib.pyplot as plt
import peakutils
import sys
import scipy.constants as cst
from pyhdf.SD import SD, SDC
from scipy.optimize import curve_fit
from scipy.ndimage import median_filter
from matplotlib.colors import LogNorm
import h5py

class Shot_information:
    """
    Stores the calibration metadata for a given OMEGA OTS campaign.

    This class selects the campaign-specific shot day, probe wavelength, and
    spectrometer configuration for the IAW and EPW diagnostics. It also builds
    the data paths used for calibration analysis and reads the experimental shot
    metadata to determine each spectrometer's central wavelength.

    Parameters
    ----------
    Campaign : str
        Campaign identifier string (e.g., 'TDYNO-22A').
    Global_loc : str
        Root directory containing the calibration files for each campaign.

    Attributes
    ----------
    Shot_day : str
        Name of the calibration dataset directory for the selected campaign.
    Harmonic : int
        Probe harmonic number used for the campaign.
    OTS_type : str
        Type of OTS configuration, either 'Temporal' or 'Spatial'.
    Experimental_shot : int
        Reference shot number used to locate the spectrometer central wavelength metadata.
    IAW_info : dict
        Calibration parameters and file names for the IAW diagnostic.
    EPW_info : dict
        Calibration parameters and file names for the EPW diagnostic.
    Calibration_region : list[int]
        Pixel region used for calibration fitting and background subtraction.
    Data_loc : str
        Full path to the campaign data directory.
    Probe_wavelength : float
        Probe wavelength in nm for the selected harmonic.
    """
    def __init__(self, Campaign, Global_loc):
        self.Campaign = Campaign
        self.Global_loc = Global_loc

        self.get_shot_info()

    def get_shot_info(self):
        self.Calibration_shot = 0
        if self.Campaign == 'TDYNO-22A':
            self.Shot_day = 'OMEGA_Jun2022'
            self.Harmonic = 4
            self.OTS_type = 'Temporal'
            self.Experimental_shot = 104470
            self.IAW_info = {
                'FWHM_file': 'iaw_4w_0o.hdf',
                'CW_file': 'iaw_tcc_263p25cw.hdf',
                'nm_per_px': -0.0044, # nm/pixel
                'time_delay': 0.78, # ns
                'grating': 3600, # g/mm
                'pinhole': 100, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.2 # ns
            }
            self.EPW_info = {
                'FWHM_file': 'epw_0cw_tcc.hdf',
                'CW_file': 'epw_100um_1202g_680um_to148_263p25.hdf',
                'nm_per_px': 0.0494, # nm/pixel
                'time_delay': 0.512, # ns
                'grating': 1200, # g/mm
                'pinhole': 150, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.033 # ns
            }
            self.Calibration_region = [400, 600, 400, 600]

        elif self.Campaign == 'TDYNO-23A':
            self.Shot_day = 'OMEGA_Jun2023'
            self.Harmonic = 2
            self.OTS_type = 'Temporal'
            self.Experimental_shot = 108616
            self.IAW_info = {
                'FWHM_file': '2160g_520cw_Ne_100umPH_IAWROSS.hdf',
                'CW_file': 'IAW_532_1o_532cw_500um_121p71_270.hdf',
                'nm_per_px': -0.00686, # nm/pixel
                'time_delay': 0.78, # ns
                'grating': 2160, # g/mm
                'pinhole': 100, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.2 # ns
            }
            self.EPW_info = {
                'FWHM_file': 'EPW_FWHM_100um_263p5cw_ross_150ph.hdf',
                'CW_file': 'EPW_align_532_1o_527cw_500um_121p71_270.hdf',
                'nm_per_px': 0.4143, # nm/pixel
                'time_delay': 0.512, # ns
                'grating': 150, # g/mm
                'pinhole': 150, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.033 # ns
            }
            self.Calibration_region = [400, 600, 400, 600]

        elif self.Campaign == 'TDYNO-24A':
            self.Shot_day = 'OMEGA_May2024'
            self.Harmonic = 2
            self.OTS_type = 'Spatial'
            self.Experimental_shot = 112005 # <- Careful as this shot day moved the EPW streak center several times
            self.IAW_info = {
                'FWHM_file': '2160g_520cw_Ne_100umSlit_IAWCCD.hdf',
                'CW_file': '2w_0cw_IAWCCD_100umslit.hdf',
                'nm_per_px': -0.00437, # nm/pixel
                'um_per_px': 2.89, # um/pixel
                'grating': 2160, # g/mm
                'slit': 100, # um
                'magnification': 4.5, 
                'spatial_resolution': np.nan # um <-- Don't know what this is
            }
            self.EPW_info = {
                'FWHM_file': '2w_0cw_EPWCCD_100umslit.hdf',
                'CW_file': '2w_0cw_EPWCCD_100umslit.hdf',
                'nm_per_px': 0.271, # nm/pixel
                'um_per_px': 5.131, # um/pixel
                'grating': 150, # g/mm
                'slit': 100, # um
                'magnification': 4.5,
                'spatial_resolution': np.nan # um <-- Don't know what this is
            }
            self.Calibration_region = [400, 600, 400, 600]

        elif self.Campaign == 'TDYNO-25A':
            self.Shot_day = 'OMEGA_May2025'
            self.Harmonic = 4
            self.OTS_type = 'Temporal'
            self.Experimental_shot = 115184
            self.IAW_info = {
                'FWHM_file': '2160g_520cw_Ne_100umPH_IAWROSS.hdf',
                'CW_file': 'IAW_ROSS_263.25cw_100ph.hdf',
                'nm_per_px': -0.00444, # nm/pixel
                'time_delay': 0.78, # ns
                'grating': 3600, # g/mm
                'pinhole': 100, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.2 # ns
            }
            self.EPW_info = {
                'FWHM_file': 'EPW_ROSS_263.25cw_150ph.hdf',
                'CW_file': 'EPW_ROSS_263.25cw_150ph.hdf',
                'nm_per_px': 0.0507, # nm/pixel
                'time_delay': 0.512, # ns
                'grating': 1200, # g/mm
                'pinhole': 150, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.033 # ns
            }
            self.Calibration_region = [400, 600, 400, 600]
            self.Calibration_region = [400, 600, 400, 600]

        elif self.Campaign == 'TDYNO-26A':
            ## I have not been given the CW files from Joe, which would be helpful to have even though they were saturated
            self.Shot_day = 'OMEGA_May2026'
            self.Harmonic = 4
            self.OTS_type = 'Temporal'
            self.Experimental_shot = 118535
            self.IAW_info = {
                'FWHM_file': 'iaw_4w_0o.hdf',
                'CW_file': 'None.hdf',
                'nm_per_px': -0.00444, # nm/pixel
                'time_delay': 0.78, # ns
                'grating': 3600, # g/mm
                'pinhole': 100, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.2 # ns
            }
            self.EPW_info = {
                'FWHM_file': 'epw_0cw_tcc.hdf',
                'CW_file': 'None.hdf',
                'nm_per_px': 0.0508, # nm/pixel
                'time_delay': 0.512, # ns
                'grating': 1200, # g/mm
                'pinhole': 150, # um
                'streak_speed': 5, # ns
                'temporal_resolution': 0.033 # ns
            }
            self.Calibration_region = [400, 600, 400, 600]

        elif self.Campaign == 'TDYNO-17A':
            self.Shot_day = 'OMEGA_April2017'
            self.Harmonic = 2
            self.OTS_type = 'Spatial'
            self.Experimental_shot = 85254 # 
            self.IAW_info = {
                'FWHM_file': '1800g_Ne_Lamp_528.hdf',
                'CW_file': 'IAW_532nmcw_tcc.hdf',
                'nm_per_px': -0.00570, # nm/pixel
                'um_per_px': np.nan, # um/pixel
                'grating': 1800, # g/mm
                'slit': 50, # um
                'magnification': 4.5, 
                'spatial_resolution': np.nan # um <-- Don't know what this is
            }
            self.EPW_info = {
                'FWHM_file': 'EPW_527nmcw_tcc.hdf',
                'CW_file': 'EPW_527nmcw_tcc.hdf',
                'nm_per_px': 0.271, # nm/pixel
                'um_per_px': np.nan, # um/pixel
                'grating': 150, # g/mm <- I'm assuming...
                'slit': 100, # um
                'magnification': 4.5,
                'spatial_resolution': np.nan # um <-- Don't know what this is
            }
            self.Calibration_region = [400, 600, 425, 625]

        self.Data_loc = os.path.join(self.Global_loc, self.Shot_day, 'Data')
        self.Probe_wavelength = 1053/self.Harmonic
        self.EPW_info['Probe_center'] = self.get_spectrometer_center('EPW')
        self.IAW_info['Probe_center'] = self.get_spectrometer_center('IAW')

    def get_spectrometer_center(self, Diagnostic):
        """
        Retrieves the spectrometer center wavelength from an experimental shot HDF file.

        This method constructs the file path for the experimental shot's HDF file and attempts to read the
        'CentralWavelength' attribute from the 'Streak_array' dataset. 

        Returns
        ----------
        Probe_center : float
            Central wavelength of the spectrometer (nm).
        """
        if self.Shot_day == 'OMEGA_April2017':
        ## Calibration data I have for this shot day was taken with the neon lamp
        ## The central wavelength are therefore as stated on the CW hdf files (eg IAW_532nmcw_tcc.hdf)
        ## For this shot day, it is best to use the stray light observed on the IAW to perform the CW calibration
            if Diagnostic == 'IAW':
                Probe_center = 532
            elif Diagnostic == 'EPW':
                Probe_center = 527
        else:
            Example_parent_loc = os.path.join(self.Data_loc, str(self.Experimental_shot), Diagnostic)
            if self.OTS_type == 'Spatial':
                File_loc = os.path.join(Example_parent_loc, f'{Diagnostic.lower()}_ccd_s{self.Experimental_shot}.hdf')
            else:
                File_loc = os.path.join(Example_parent_loc, f'{Diagnostic.lower()}_s{self.Experimental_shot}.hdf')
            if not os.path.exists(File_loc):
                File_loc = File_loc.replace('.hdf', '.h5')

            if '.hdf' in File_loc:
                hdf = SD(File_loc, SDC.READ)
                data = hdf.select('Streak_array')
                data_attributes = data.attributes()
                Probe_center = data_attributes['CentralWavelength']
            elif '.h5' in File_loc:
                hdf = h5py.File(File_loc, 'r')
                data = hdf['Streak_array']
                data_attributes = data.attrs
                Probe_center = data_attributes['CentralWavelength']
            if Diagnostic == 'IAW':
                ## For some reason a few of the IAW CentralWavelength values are incorrect
                ## So override with the probe wavelength (which is essentially all we ever do for IAW)
                if self.Shot_day == 'OMEGA_Jun2022' or self.Shot_day == 'OMEGA_May2024':
                    Probe_center = self.Probe_wavelength
        print(f"{Diagnostic} spectrometer center wavelength: {Probe_center:3g} nm")
        return Probe_center

class Calibration_analysis:
    """
    Performs calibration analysis for IAW and EPW diagnostics.

    This class processes calibration images to extract key spectrometer parameters,
    including the central wavelength and full width at half maximum (FWHM), using 
    Gaussian fitting and background subtraction. It supports visualization and saving 
    of calibration results.

    Parameters
    ----------
    Shot_info : class
        Shot_info instance containing information about the shot.
    Save_bool : bool
        If True, saves generated calibration information.
    """
    ## This class provides the calibration analysis for the IAW and EPW diagnostics

    def __init__(self, Shot_info, Save_bool):
        self.Shot_info = Shot_info
        self.Save_bool = Save_bool
        self.extract_info()

        self.perform_analysis()
        plt.show()

    def extract_info(self):
        """
        Extracts information from Shot_info class
        """
        self.Global_loc = self.Shot_info.Global_loc
        self.Campaign = self.Shot_info.Campaign
        self.Data_loc = self.Shot_info.Data_loc
        self.Calibration_shot = self.Shot_info.Calibration_shot
        self.Calibration_region = self.Shot_info.Calibration_region
        self.Shot_day = self.Shot_info.Shot_day
        self.OTS_type = self.Shot_info.OTS_type
        self.Harmonic = self.Shot_info.Harmonic
        self.Probe_wavelength = self.Shot_info.Probe_wavelength
        self.EPW_info = self.Shot_info.EPW_info
        self.IAW_info = self.Shot_info.IAW_info

    def perform_analysis(self):
        """
        Performs the calibration analysis for both IAW and EPW diagnostics.
        """
        # for Diagnostic in ['IAW']:  # Only process IAW for now
        for Diagnostic in ['IAW', 'EPW']:
            self.Diagnostic = Diagnostic
            self.Parent_loc = os.path.join(self.Data_loc, str(self.Calibration_shot), self.Diagnostic)
            self.Spectrometer = self.IAW_info if self.Diagnostic == 'IAW' else self.EPW_info
            self.FWHM_image = self.read_hdf(os.path.join(self.Parent_loc, self.Spectrometer['FWHM_file']), filetype='FWHM')
            if self.Campaign == 'TDYNO-26A':
                self.Alignment_image = np.zeros_like(self.FWHM_image)
            else:
                self.Alignment_image = self.read_hdf(os.path.join(self.Parent_loc, self.Spectrometer['CW_file']), filetype='Alignment')
            self.perform_calibration(calibration_region=self.Calibration_region)
            if self.Save_bool:
                self.write_info_file()
            # sys.exit()

    def read_hdf(self, File_loc, filetype=None, plot=True):
        """
        This function opens the specified HDF file, extracts the first data group, and retrieves the raw and pre-shot images.
        It subtracts the background (pre-shot) image from the raw image, sets negative values to zero, and normalizes the result.
        If `plot` is True, the processed image is displayed using matplotlib.

        Parameters
        ----------
        File_loc : str
            Path to the HDF file to be read.
        filetype : str, optional
            A string indicating the type of the file (e.g., 'FWHM', 'Alignment').
        plot : bool, optional
            If True, displays a plot of the processed data image (default is False).

        Returns
        -------
        data_image : numpy.ndarray
            The processed image data with background subtracted and negative values set to zero.
        """
        print(f"Reading HDF file: {File_loc}")
        hdf = SD(File_loc, SDC.READ)
        hdf_object = hdf.datasets()
        
        ## Get list of data groups stored in hdf file
        obj_groups = [k for k in hdf_object.keys()]
        print(f"\tData groups in HDF file: {obj_groups}")

        ## Extracting real data from the hdf
        data = hdf.select('Streak_array')
        data_array = np.array(data.get(), dtype=np.float64)

        ## Data image taken during shot
        raw_image = data_array[0]
        ## Background image taken prior to shot
        pre_shot = data_array[1]
        data_image = raw_image - pre_shot
        data_image[data_image < 0] = 0
        data_image = data_image - np.min(data_image)

        if plot:
            fig, axs = plt.subplots(figsize=(5, 4))
            im = axs.imshow(data_image+1e-1, cmap='inferno', origin='lower', norm=LogNorm(vmin=10))
            plt.colorbar(im, ax=axs)
            rect = plt.Rectangle((self.Calibration_region[2], self.Calibration_region[0]), self.Calibration_region[3]-self.Calibration_region[2], self.Calibration_region[1]-self.Calibration_region[0], 
                                 linewidth=2, edgecolor='white', linestyle='--', facecolor='none', label='Calibration region')
            axs.add_patch(rect)
            axs.set_aspect('equal', adjustable='box')
            axs.minorticks_on()
            axs.tick_params(axis='both', which='major', length=10, direction='in', top=True, right=True, color='white')
            axs.tick_params(axis='both', which='minor', length=5, direction='in', top=True, right=True, color='white')
            plt.legend(loc='upper right', fontsize=10)
            plt.suptitle('{} Calibration {}\n{}'.format(filetype, self.Diagnostic, File_loc.replace(f"{self.Parent_loc}/", '')))
            axs.set_xlabel('X Pixels')
            axs.set_ylabel('Y Pixels')
            if self.Save_bool:
                file = File_loc.replace('.hdf', f'_{filetype}.png')
                plt.savefig(file, dpi=300, bbox_inches='tight')
        return data_image
    
    def perform_calibration(self, calibration_region=[400, 600, 400, 600], plot=True):
        """
        Performs calibration analysis on the provided data images within a specified pixel region.
        This method processes both the FWHM and alignment images to extract calibration parameters,
        including the central wavelength and FWHM. Optionally, it generates diagnostic plots
        visualizing the calibration results.
        
        Parameters
        ----------
        calibration_region : list of int, optional
            The [y-start, y-end, x-start, x-end] pixel range for calibration analysis. Default is [400, 600, 400, 600].
        plot : bool, optional
            If True, generates diagnostic plots of the calibration analysis. Default is True.
        
        Notes
        -----
        - Updates instance attributes: Central_wavelength and FWHM.
        - If `plot` is True, displays and optionally saves calibration analysis figures.
        """   
        Probe_pix_loc_fwhm, Central_wavelength_fwhm, Gaus_params_fwhm, Signal_fit_fwhm, Signal_sum_fwhm = self.process_image(self.FWHM_image, calibration_region, type='FWHM')
        if self.Campaign == 'TDYNO-26A':
            ## This is calibration info provided by Joe           
            # IAW calibration   y=mx+b   m= -0.00444 nm/px and b = 265.6863 nm
            # EPW calibration m = 0.0508 nm/px b = 202.7nm

            m = self.Spectrometer['nm_per_px']
            if self.Diagnostic == 'IAW':
                b = 265.6863
            elif self.Diagnostic == 'EPW':
                b = 202.7

            Probe_pix_loc_align = (self.Probe_wavelength - b) / m
            Central_wavelength_align = self.FWHM_image.shape[0]//2 * m + b
        else:
            Probe_pix_loc_align, Central_wavelength_align, Gaus_params_align, Signal_fit_align, Signal_sum_align = self.process_image(self.Alignment_image, calibration_region, type='CW')

        Probe_pix_loc = Probe_pix_loc_align
        Central_wavelength = Central_wavelength_align
        popt_gaus = Gaus_params_fwhm

        FWHM = 2 * np.sqrt(2 * np.log(2)) * popt_gaus[-1]
        Input_FWHM = popt_gaus[-1] ## For GGs code

        if self.Campaign == 'TDYNO-25A' and self.Diagnostic == 'IAW':
            ## Correcting FWHM for the TDYNO-25A campaign as the calibration file was taken with a different grating
            ## So determine the size of the pinhole in pixels on the detector (with the calibration file grating dispersion)
            Pixel_FWHM = FWHM / 0.00686 # size of the pinhole on the detector in pixels
            ## Then convert to the FWHM corresponding to the actual spectrometer grating
            FWHM = np.abs(Pixel_FWHM * self.Spectrometer['nm_per_px'])

        self.Spectrometer['FWHM'] = FWHM
        self.Spectrometer['CW'] = Central_wavelength
        self.Spectrometer['Probe_pix_loc'] = int(Probe_pix_loc)

        if plot == True:
            fig, axs = plt.subplots(2, 2, figsize=(11, 9))

            def add_image(ax, image, central_wavelength, fit, sum, cmap='inferno', title='Image'):
                if self.OTS_type == 'Temporal':
                    ax.imshow(image.T, cmap=cmap, origin='lower', extent=[fit[0][0], fit[0][-1], 0, image.shape[1]],
                              vmin=np.nanmin(image[calibration_region[0]:calibration_region[1], calibration_region[2]:calibration_region[3]]), vmax=np.nanmax(image[calibration_region[0]:calibration_region[1], calibration_region[2]:calibration_region[3]]))
                    ax.set_ylabel('X Pixels')  
                elif self.OTS_type == 'Spatial':
                    ax.imshow(image, cmap=cmap, origin='lower', extent=[fit[0][0], fit[0][-1], 0, image.shape[0]],
                              vmin=np.nanmin(image[calibration_region[0]:calibration_region[1], calibration_region[2]:calibration_region[3]]), vmax=0.5*np.nanmax(image[calibration_region[0]:calibration_region[1], calibration_region[2]:calibration_region[3]]))
                    ax.set_ylabel('Y Pixels')  
                ax.axvline(central_wavelength, color='red', linestyle='--', label='Image centre', alpha=0.7)
                ax.axvline(self.Spectrometer['Probe_center'], color='cyan', linestyle='--', label='Probe centre', alpha=0.7)
                ax.plot(fit[0], calibration_region[1]-50+sum*20, ':', color='white', label='Raw Signal')
                ax.plot(fit[0], calibration_region[1]-50+fit[1]*20, color='limegreen')
                leg = ax.legend(loc='upper right')
                ax.add_artist(leg)
                ax.set_xlabel('Wavelength (nm)')        
                ax.set_aspect('auto', adjustable='box')
                ax.set_title(f'{title}')
            
            def add_fit(ax, central_wavelength, fit, sum, fwhm, fittype='FWHM'):
                ax.plot(fit[0], sum, 'k.', label='Raw Signal')
                ax.plot(fit[0], fit[1], 'g-', label='Gaussian Fit')
                ax.axvline(central_wavelength, color='red', linestyle='--', alpha=0.7)
                ax.axvline(self.Spectrometer['Probe_center'], color='cyan', linestyle='--', alpha=0.7)           
                if fittype == 'FWHM':
                    ax.set_title('FWHM from Gaussian Fit = {:.4g} nm'.format(fwhm))
                elif fittype == 'CW':
                    ax.set_title('Central Wavelength = {:.2f} nm'.format(central_wavelength))
                leg = ax.legend(loc='upper right')
                ax.add_artist(leg)
                ax.set_xlabel('Wavelength (nm)')
                ax.set_ylabel('Intensity')

            if not self.Campaign == 'TDYNO-26A':
                add_image(axs[0, 0], self.Alignment_image, Central_wavelength_align, Signal_fit_align, Signal_sum_align, title='CW Alignment Image')
                add_fit(axs[1, 0], Central_wavelength_align, Signal_fit_align, Signal_sum_align, 2 * np.sqrt(2 * np.log(2)) * Gaus_params_align[-1], fittype='CW')

            add_image(axs[0, 1], self.FWHM_image, Central_wavelength_fwhm, Signal_fit_fwhm, Signal_sum_fwhm, title='FWHM Image')
            add_fit(axs[1, 1], Central_wavelength_fwhm, Signal_fit_fwhm, Signal_sum_fwhm, FWHM, fittype='FWHM')

            for a in axs.flat:
                a.minorticks_on()
                a.tick_params(axis='both', which='major', length=10, direction='in', top=True, right=True)
                a.tick_params(axis='both', which='minor', length=5, direction='in', top=True, right=True)
                if self.Diagnostic == 'IAW':
                    if self.Harmonic == 4:
                        s = 0.35
                    elif self.Harmonic == 2:
                        s = 0.35
                elif self.Diagnostic == 'EPW':
                    if self.Harmonic == 4:
                        s = 2.5
                    elif self.Harmonic == 2:
                        s = 20
                a.set_xlim(Central_wavelength-s, Central_wavelength+s)
            for a in axs[0, :].flat:
                a.tick_params(which='both', color='white')
                a.set_ylim(calibration_region[0]+70, calibration_region[1]+15) 
            plt.suptitle('{} Calibration Analysis'.format(self.Diagnostic), fontsize=16)
            if self.Save_bool:
                plt.savefig(os.path.join(self.Parent_loc, f'{self.Diagnostic}_calibration_analysis.png'), dpi=300, bbox_inches='tight')

    def process_image(self, Image, calibration_region, type='FWHM', plot=False):
        """
        Processes a calibration image to determine its central wavelength and full width at half maximum (FWHM).

        Parameters
        ----------
        Image : numpy.ndarray
            2D array representing the calibration image.
        calibration_region : tuple or list
            Indices specifying the region of interest for calibration (y_start, y_end, x_start, x_end).
        plot : bool, optional
            If True, plots intermediate results for diagnostic purposes (default is False).

        Returns
        -------
        Probe_pix_loc : int
            Pixel location of the probe center.
        Central_wavelength : float
            Central wavelength of the calibration image.
        popt_gaus : list
            Optimal parameters for the fitted Gaussian [amplitude, center, width].
        [Wavelength, Fit] : list
            Arrays of wavelength values and corresponding fitted Gaussian values.
        Raw_signal : numpy.ndarray
            Signal along wavelength axis.
        """
        # ## Suppress isolated salt-and-pepper pixels while preserving the
        # ## calibration feature for subsequent summation and fitting.
        # Image = median_filter(np.asarray(Image), size=3, mode='nearest')

        ## Masking the image to central calibration area
        Image_mask = np.zeros_like(Image)
        Image_mask[calibration_region[0]:calibration_region[1], calibration_region[2]:calibration_region[3]] = 1
        Nan_image = Image * Image_mask

        show_image = Nan_image.copy()
        show_image[show_image == 0] = np.nan

        def strip_sum(image, calibration_pixels, axis=0, polyfit=1, plot=plot):
            ## Summing the calibration signal along one axis 
            ## and performing crude background removal
            Sum = np.nansum(image, axis=axis)
            Sum /= np.nanmax(Sum)
            Fit_sum = Sum.copy()

            def signal_fit(x, amp, mu, std, slope, offset):
                gaus = np.exp(-((x - mu) ** 2) / (2 * std ** 2))
                gaus /= np.nanmax(gaus)
                gaus *= amp
                bkgd = slope*x + offset
                return gaus + bkgd

            # Fit_sum[Fit_sum >= 0.05 * np.max(Fit_sum)] = np.mean(Fit_sum[calibration_pixels[0]-100:calibration_pixels[0]])
            Fit_sum = Fit_sum[calibration_pixels[0]:calibration_pixels[1]]
            Fit_pxs = np.arange(calibration_pixels[0], calibration_pixels[1], 1)
            popt, pcov = curve_fit(signal_fit, Fit_pxs, Fit_sum, p0=[1, np.nanargmax(Fit_sum)+calibration_pixels[0], 5, 0, np.nanmin(Fit_sum)], 
                                   bounds=([0, calibration_pixels[0], 0, -np.inf, -np.inf], [np.inf, calibration_pixels[1], np.inf, np.inf, np.inf]))
            fit = signal_fit(Fit_pxs, *popt)
            background = signal_fit(Fit_pxs, 0, *popt[1:])
            if plot:
                plt.figure()
                plt.plot(Sum[calibration_pixels[0]:calibration_pixels[1]], 'k-', label='Summed signal')
                plt.plot(fit, 'b-.', label='Signal fit')
                plt.plot(background, 'r--', label='Background fit')
                plt.legend()
                plt.suptitle('Checking background fit to signal along axis {}'.format(axis))
                plt.show()
                # sys.exit()
            Sum[calibration_pixels[0]:calibration_pixels[1]] = Sum[calibration_pixels[0]:calibration_pixels[1]] - background
            return Sum/np.max(Sum)

        Sum_X = strip_sum(Nan_image, calibration_pixels=[calibration_region[2], calibration_region[3]], axis=0, polyfit=1)
        Sum_Y = strip_sum(Nan_image, calibration_pixels=[calibration_region[0], calibration_region[1]], axis=1, polyfit=1)

        if self.OTS_type == 'Temporal':
            Raw_signal = Sum_Y
        elif self.OTS_type == 'Spatial':
            Raw_signal = Sum_X

        Raw_signal[Raw_signal < 0] = 0
        Pixels = np.arange(0, len(Raw_signal), 1) # This assumes square image
        Peak_pixel = np.argmax(Raw_signal)

        if self.Campaign == 'TDYNO-25A' and self.Diagnostic == 'IAW' and type=='FWHM':
                ## The FWHM used for this campaign was taken with a 2160 grating with a different dispersion
                ## This is then corrected later
                Wavelength_per_pixel = -0.00686
        else:
            Wavelength_per_pixel = self.Spectrometer['nm_per_px']

        Probe_center = self.Spectrometer['Probe_center']
        ## Initial guess of central wavelength
        Lambdas = Pixels * Wavelength_per_pixel
        Lambdas_peak = Lambdas[Peak_pixel]
        Shift = Probe_center - Lambdas_peak
        Wavelength = Lambdas + Shift

        ## Fitting a Gaussian to the instrument function
        popt_gaus, pcov_gaus = curve_fit(self.gaussian, Wavelength, Raw_signal, p0=[1, Probe_center, 0.1], bounds=([0, 0, 0], [np.inf, np.inf, np.inf]))
        fit_gaussian = self.gaussian(Wavelength, *popt_gaus)
        FWHM = 2 * np.sqrt(2 * np.log(2)) * popt_gaus[-1]
        Input_FWHM = popt_gaus[-1]
        Fit = fit_gaussian

        Lambdas_peak = Lambdas[np.argmax(fit_gaussian)]
        Shift = Probe_center - Lambdas_peak
        Wavelength = Lambdas + Shift
        Central_wavelength = Shift + Wavelength_per_pixel*np.shape(Image)[1] / 2
        Probe_pix_loc = np.argmax(fit_gaussian)

        # if self.Diagnostic == 'IAW' and self.Shot_day == 'OMEGA_Jun2023':
        #     ## There is a double peak feature in this IAW calibration data..
        #     Indexes = peakutils.peak.indexes(Raw_signal, min_dist=5, thres=0.85)[:]
        #     Peak = int(((Indexes[0]+Indexes[1])/2))
        #     popt_gaus, pcov_gaus = curve_fit(self.gaussian, Wavelength[Peak:], Raw_signal[Peak:], p0=[1, Probe_center, 0.1], bounds=([0, 0, 0], [np.inf, np.inf, np.inf]))
        #     fit_gaussian = self.gaussian(Wavelength, *popt_gaus)
        #     FWHM = 2 * np.sqrt(2 * np.log(2)) * popt_gaus[-1]
        #     Input_FWHM = popt_gaus[-1]
        #     Fit = fit_gaussian

        return Probe_pix_loc, Central_wavelength, popt_gaus, [Wavelength, Fit], Raw_signal

    def write_info_file(self):
        """
        Writes the calibration information to a text file.
        """
        file = os.path.join(self.Parent_loc, f'{self.Diagnostic}_calibration_info.txt')
        if os.path.exists(file):
            os.remove(file)
        with open(file, 'w') as f:
            f.write(f"## {self.Harmonic}w {self.OTS_type} {self.Diagnostic} information\n")
            f.write(f"## Taken from {self.Campaign} shot day\n\n")
            f.write("Calibration Files:\n")
            f.write(f"\tInstrument FWHM = {self.Spectrometer['FWHM_file']}\n")
            f.write(f"\tCentral wavelength alignment = {self.Spectrometer['CW_file']}\n")
            f.write("\nSpectrometer Setup:\n")
            f.write(f"\tGrating = {self.Spectrometer['grating']} g/mm\n")
            f.write(f"\tWavelength per pixel = {self.Spectrometer['nm_per_px']} nm/pixel\n")
            if self.OTS_type == 'Spatial':
                f.write(f"\tSlit width = {self.Spectrometer['slit']} um\n")
                f.write(f"\tMagnification = {self.Spectrometer['magnification']}\n")
                f.write(f"\tSpatial resolution = {self.Spectrometer['spatial_resolution']} um\n")
                f.write(f"\tSpatial per pixel = {self.Spectrometer['um_per_px']} um/pixel\n\n")
            elif self.OTS_type == 'Temporal':
                f.write(f"\tPinhole diameter = {self.Spectrometer['pinhole']} um\n")
                f.write(f"\tStreak speed = {self.Spectrometer['streak_speed']} ns\n")
                f.write(f"\tStreak temporal resolution = {self.Spectrometer['temporal_resolution']} ns\n")
                f.write(f"\tTime delay = {self.Spectrometer['time_delay']} ns\n\n")
            f.write("Calibration Results:\n")
            f.write(f"\tGaussian instrument FWHM = {self.Spectrometer['FWHM']:.4g} nm\n")
            f.write(f"\tCentral pixel wavelength = {self.Spectrometer['CW']:.2f} nm\n")
            f.write(f"\tPixel location of OTS probe = {self.Spectrometer['Probe_pix_loc']}\n")
        f.close()
        print(f"{self.Diagnostic} Calibration information saved to: {file}")

    @staticmethod
    def lorentz(x, amp, gamma):
        """
        Computes a Lorentzian function for the given input array.

        Parameters
        ----------
        x : array-like
            The input values at which to evaluate the Lorentzian function.
        amp : float
            The amplitude (height) of the Lorentzian peak.
        gamma : float
            The full width at half maximum (FWHM) of the peak.

        Returns
        -------
        array : ndarray
            The computed Lorentzian values for each element in `x`.
        """
        g = gamma / 2
        array = (amp * g) / (cst.pi * (x**2 + g**2))
        return array

    @staticmethod
    def gaussian(x, amp, mu, std):
        """
        Computes a Gaussian function for the given input array.

        Parameters
        ----------
        x : array-like
            The input values at which to evaluate the Gaussian function.
        amp : float
            The amplitude (height) of the Gaussian peak.
        mu : float
            The mean (center) of the Gaussian distribution.
        std : float
            The standard deviation (width) of the Gaussian distribution.

        Returns
        -------
        array : ndarray
            The computed Gaussian values for each element in `x`.
        """
        array = amp * np.exp(-((x - mu) ** 2) / (2 * std ** 2))
        return array

if __name__ == "__main__":
    #%%
    ## Import data
    ###############################################################
    ##                                                           ##
    ##                        DATA TO INPUT                      ##
    ##                                                           ##
    ###############################################################

    ## Define the shot day, shot number, and diagnostic
    Campaigns = ['TDYNO-17A', 'TDYNO-22A', 'TDYNO-23A', 'TDYNO-24A', 'TDYNO-25A', 'TDYNO-26A']

    ## If you want to save output figures and info
    Save_bool = False

    ## Define the location of the data files
    User = 'hpoole'
    Global_loc = os.path.join('/', 'Users', User, 'Library', 'CloudStorage', 'Box-Box', 'TDYNO_NLUF', 'OMEGA')

    ###############################################################
    
    #%%
    for Campaign in Campaigns:
        ## Run the calibration analysis
        ###############################################################
        ##                                                           ##
        ##                    PERFORM ANALYSIS                       ##
        ##                                                           ##
        ###############################################################
        
        Shot_info = Shot_information(Campaign, Global_loc)
        Calibration = Calibration_analysis(Shot_info, Save_bool)

        ################################################################
        
        ###############################################################
        ##                                                           ##
        ##                   PRINT CALIBRATION                       ##
        ##                                                           ##
        ###############################################################
        
        for Diagnostic in ['IAW', 'EPW']:
            calibration_file = os.path.join(Calibration.Data_loc, str(Calibration.Calibration_shot), Diagnostic, f'{Diagnostic}_calibration_info.txt')
            with open(calibration_file, 'r') as f:
                print(f"\n###########################################")
                print(f"###\t{Diagnostic} Calibration Information\t###")
                print(f"###########################################\n")
                print(f.read())
                print(f"###########################################\n")
