## MCMC log-likelihood function and gradient using PyTensor for EPW
## Generated by: H. Poole

import numpy as np
import os
import pandas as pd
sdk = os.popen("xcrun --show-sdk-path").read().strip()
import pytensor
pytensor.config.cxx = "/usr/bin/clang++"
pytensor.config.gcc__cxxflags = f"-I{sdk}/usr/include/c++/v1"
import pytensor.tensor as pt
from pytensor.graph import Apply, Op
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'Libraries'))
from OTS_function import OTS
from normalisation import Data_normalisation

## Log-likelihood function for IAW without gradient

def loglike(params, x, data_err, data):
    """
    Computes the log-likelihood of observed data given a model for Thomson scattering analysis.

    This function generates a model spectrum using the provided plasma parameters and compares it to the observed data,
    returning the log-likelihood value. It performs input type checking, interpolates the model to the data points,
    applies scaling, and evaluates the likelihood.

    Parameters
    ----------
    params : array
        Array of plasma parameters e.g. [te, ti, ne, e_cur, flow, v_grad].
    x : np.ndarray
        Wavelength or position array for interpolation.
    data_err : np.ndarray
        Uncertainties associated with the observed data.
    data : np.ndarray
        Observed data to be fitted.

    Returns
    -------
    float
        The log-likelihood value comparing the model to the observed data.

    Raises
    ------
    TypeError
        If any input parameter is not a float or np.ndarray.
    """

    fitting_info = pd.read_csv('MCMC_fitting_info.csv', index_col=None)
    param_mins = fitting_info['mins'].values
    param_maxs = fitting_info['maxs'].values
    param_names = fitting_info['names'].values
    param_logbool = fitting_info['logbool'].values
    sigma = fitting_info['sigma'].values[0]

    orig_params = []
    for i, param in enumerate(params):
        arr = np.asarray(param)
        if arr.ndim >= 1 and arr.size == 1:
            param = arr.item()
        orig_params.append(Data_normalisation().unnormalise_data(param, param_mins[i], param_maxs[i], log=param_logbool[i]))

    model_x, model_y = generate_fit(orig_params, param_names)
    model = np.interp(x, model_x*1e9, model_y)
    scaled_model = Fit_OTS().scalings(sigma, data, data_err, model)
    cost = np.asarray(Fit_OTS().likelihood(sigma, scaled_model, data, data_err), dtype=data.dtype)

    return cost

def generate_fit(params, names):
    from run import Initialization
    INIT = Initialization()
    ots_model = INIT.OTS_model  # Create an instance of OTS with initialization
    model_x, model_y = ots_model.run_fitting(params, names)
    return model_x, model_y

class LogLike_nograd(Op):
    """
    A PyTensor Op for computing the log-likelihood of a model without gradient support.

    This class wraps a custom log-likelihood function (`loglike`) for use in PyTensor computational graphs,
    allowing it to be used in probabilistic programming or MCMC workflows where gradients are not required.
    The Op takes as input a set of model parameters and data arrays, and outputs the computed log-likelihood.

    Methods
    -------
    make_node(te, ti, ne, e_cur, flow, v_grad, sigma, core, x, data_err, data)
        Constructs a PyTensor Apply node for the log-likelihood computation, converting all inputs to tensor variables.

    perform(node, inputs, outputs)
        Numerically evaluates the log-likelihood using the provided numpy arrays and stores the result in outputs.

    Parameters
    ----------
    te : array-like
        Electron temperature(s).
    ti : array-like
        Ion temperature(s).
    ne : array-like
        Electron density(ies).
    e_cur : array-like
        Current or energy parameter(s).
    flow : array-like
        Flow velocity(ies).
    v_grad : array-like
        Velocity gradient(s).
    sigma : array-like
        Broadening parameter(s).
    core : array-like
        Core parameter(s).
    x : array-like
        Independent variable(s) (e.g., wavelength or position).
    data_err : array-like
        Measurement uncertainties.
    data : array-like
        Observed data to fit.

    Returns
    -------
    loglike_eval : array-like
        The computed log-likelihood values, with the same shape and dtype as the input data.
    """
    def make_node(self, params, x, data_err, data) -> Apply:
        # Convert inputs to tensor variables
        params = [pt.as_tensor(p) for p in params]
        x = pt.as_tensor(x)
        data_err = pt.as_tensor(data_err)
        data = pt.as_tensor(data)

        inputs = []
        inputs.extend(params)
        inputs.append(x)
        inputs.append(data_err)
        inputs.append(data)

        # Define output type, in our case a vector of likelihoods
        # with the same dimensions and same data type as data
        # If data must always be a vector, we could have hard-coded
        # outputs = [pt.vector()]
        outputs = [data.type()]

        # Apply is an object that combines inputs, outputs and an Op (self)
        return Apply(self, inputs, outputs)

    def perform(self, node: Apply, inputs: list[np.ndarray], outputs: list[list[None]]) -> None:
        # This is the method that compute numerical output
        # given numerical inputs. Everything here is numpy arrays
        params = inputs[:-3]  # all but last 3 inputs are params
        x, data_err, data = inputs[-3:]  # last 3 inputs
        # params, x, data_err, data = inputs  # this will contain my variables

        # call our numpy log-likelihood function
        loglike_eval = loglike(params, x, data_err, data)

        # Save the result in the outputs list provided by PyTensor
        # There is one list per output, each containing another list
        # pre-populated with a `None` where the result should be saved.
        outputs[0][0] = np.asarray(loglike_eval)

class Fit_OTS:

    def likelihood(self, sigma, Fit, Data, Data_err):
        # Calculate the difference between model and experimental data, normalised by the experimental error
        dif = np.divide(Data - Fit, Data_err, where=Data_err != 0, out=np.zeros_like(Data_err))
        # per = np.where(Data_err != 0, (Data - Fit) / (Data * Data_err), 0)

        # Compute the likelihood term based on the condition
        SB = [
            np.power(dif[i] / (np.sqrt(2) * sigma), 2) + np.log(np.sqrt(2 * np.pi)) + np.log(sigma) if Data[
                                                                                                           i] > np.nanmax(
                Data) * 0.1 else np.log(np.sqrt(2 * np.pi)) + np.log(sigma)
            for i in range(len(Fit))
        ]

        return -np.asarray(SB)

    def scalings(self, sigma, Data_y, Data_err, Fit_y):
        Peak_signal = np.where(Data_y == np.nanmax(Data_y))[0][0]
        Peak_data_signal = Data_y[Peak_signal]
        Peak_error = Data_err[Peak_signal]
        Scalings = np.random.normal(Peak_data_signal, Peak_error, size=500)
        Scales = (np.zeros(len(Scalings)) + 1) / Scalings
        Scaled_fit_signals = np.array([s * Fit_y for s in Scales])

        Data_signals = np.tile(Data_y, (len(Scalings), 1))
        Data_errors = np.tile(Data_err, (len(Scalings), 1))

        calc = np.divide((Data_signals - Scaled_fit_signals), Data_errors, where=Data_errors != 0, out=np.zeros_like(Data_errors))
        # calc = np.where(Data_errors != 0, (Data_signals - Scaled_fit_signals) / (Data_errors), 0)
        costs = np.power(calc / (np.sqrt(2) * sigma), 2)
        sums = np.nansum(costs, axis=1)
        loc = np.argmin(sums)
        # maxs = np.nanmax(costs, axis=1)
        # loc = np.argmin(maxs)
        # Cost = maxs[loc]
        Scale = Scales[loc]
        Fit_y = Scale * Fit_y

        return Fit_y