## MCMC log-likelihood function and gradient using PyTensor for IAW
## Generated by: H. Poole

import numpy as np
import os
sdk = os.popen("xcrun --show-sdk-path").read().strip()
import pytensor
pytensor.config.cxx = "/usr/bin/clang++"
pytensor.config.gcc__cxxflags = f"-I{sdk}/usr/include/c++/v1"
import pytensor.tensor as pt
from pytensor.graph import Apply, Op
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'Libraries'))
from OTS_function import OTS
from normalisation import Data_normalisation

## Log-likelihood function for IAW without gradient

def loglike(params, x, data_err, data):
    """
    Computes the log-likelihood of observed data given a model for Thomson scattering analysis.

    This function generates a model spectrum using the provided plasma parameters and compares it to the observed data,
    returning the log-likelihood value. It performs input type checking, interpolates the model to the data points,
    applies scaling, and evaluates the likelihood.

    Parameters
    ----------
    params : array
        Array of plasma parameters e.g. [te, ti, ne, e_cur, flow, v_grad].
    x : np.ndarray
        Wavelength or position array for interpolation.
    data_err : np.ndarray
        Uncertainties associated with the observed data.
    data : np.ndarray
        Observed data to be fitted.

    Returns
    -------
    float
        The log-likelihood value comparing the model to the observed data.

    Raises
    ------
    TypeError
        If any input parameter is not a float or np.ndarray.
    """

    from run import Exploration, Initialization
    EXPLORE = Exploration()
    INIT = Initialization()
    model = INIT.OTS_model  # Create an instance of OTS with initialization

    orig_params = []
    for i, param in enumerate(params):
        arr = np.asarray(param)
        if arr.ndim >= 1 and arr.size == 1:
            param = arr.item()
        orig_params.append(Data_normalisation().unnormalise_data(param, EXPLORE.param_mins[i], EXPLORE.param_maxs[i], log=EXPLORE.param_logbool[i]))

    model_x, model_y = model.run_fitting(orig_params, EXPLORE.param_names, use_zbar_eos=True, use_range=True)
    model = np.interp(x, model_x*1e9, model_y)
    scaled_model = Fit_OTS().scalings(EXPLORE.sigma, data, data_err, model)
    cost = np.asarray(Fit_OTS().likelihood(EXPLORE.sigma, scaled_model, data, data_err), dtype=data.dtype)

    return cost

class LogLike_nograd(Op):
    """
    A PyTensor Op for computing the log-likelihood of a model without gradient support.

    This class wraps a custom log-likelihood function (`loglike`) for use in PyTensor computational graphs,
    allowing it to be used in probabilistic programming or MCMC workflows where gradients are not required.
    The Op takes as input a set of model parameters and data arrays, and outputs the computed log-likelihood.

    Methods
    -------
    make_node(te, ti, ne, e_cur, flow, v_grad, sigma, core, x, data_err, data)
        Constructs a PyTensor Apply node for the log-likelihood computation, converting all inputs to tensor variables.

    perform(node, inputs, outputs)
        Numerically evaluates the log-likelihood using the provided numpy arrays and stores the result in outputs.

    Parameters
    ----------
    te : array-like
        Electron temperature(s).
    ti : array-like
        Ion temperature(s).
    ne : array-like
        Electron density(ies).
    e_cur : array-like
        Current or energy parameter(s).
    flow : array-like
        Flow velocity(ies).
    v_grad : array-like
        Velocity gradient(s).
    sigma : array-like
        Broadening parameter(s).
    core : array-like
        Core parameter(s).
    x : array-like
        Independent variable(s) (e.g., wavelength or position).
    data_err : array-like
        Measurement uncertainties.
    data : array-like
        Observed data to fit.

    Returns
    -------
    loglike_eval : array-like
        The computed log-likelihood values, with the same shape and dtype as the input data.
    """
    def make_node(self, params, x, data_err, data) -> Apply:
        # Convert inputs to tensor variables
        params = [pt.as_tensor(p) for p in params]
        x = pt.as_tensor(x)
        data_err = pt.as_tensor(data_err)
        data = pt.as_tensor(data)

        inputs = []
        inputs.extend(params)
        inputs.append(x)
        inputs.append(data_err)
        inputs.append(data)

        # Define output type, in our case a vector of likelihoods
        # with the same dimensions and same data type as data
        # If data must always be a vector, we could have hard-coded
        # outputs = [pt.vector()]
        outputs = [data.type()]

        # Apply is an object that combines inputs, outputs and an Op (self)
        return Apply(self, inputs, outputs)

    def perform(self, node: Apply, inputs: list[np.ndarray], outputs: list[list[None]]) -> None:
        # This is the method that compute numerical output
        # given numerical inputs. Everything here is numpy arrays
        params = inputs[:-3]  # all but last 3 inputs are params
        x, data_err, data = inputs[-3:]  # last 3 inputs
        # params, x, data_err, data = inputs  # this will contain my variables

        # call our numpy log-likelihood function
        loglike_eval = loglike(params, x, data_err, data)

        # Save the result in the outputs list provided by PyTensor
        # There is one list per output, each containing another list
        # pre-populated with a `None` where the result should be saved.
        outputs[0][0] = np.asarray(loglike_eval)

class Fit_OTS:

    def likelihood(self, sigma, Fit, Data, Data_err):
        # Calculate the difference between model and experimental data, normalised by the experimental error
        dif = (Data - Fit) / Data_err
        per = (Data - Fit) / (Data*Data_err)

        # Compute the likelihood term based on the condition
        SB = [
            np.power(dif[i] / (np.sqrt(2) * sigma), 2) + np.log(np.sqrt(2 * np.pi)) + np.log(sigma) if Data[
                                                                                                           i] > np.nanmax(
                Data) * 0.1 else np.log(np.sqrt(2 * np.pi)) + np.log(sigma)
            for i in range(len(Fit))
        ]

        return -np.asarray(SB)

    def scalings(self, sigma, Data_y, Data_err, Fit_y):
        Peak_signal = np.where(Data_y == np.nanmax(Data_y))[0][0]
        Peak_data_signal = Data_y[Peak_signal]
        Peak_error = Data_err[Peak_signal]
        Scalings = np.random.normal(Peak_data_signal, Peak_error, size=500)
        Scales = (np.zeros(len(Scalings)) + 1) / Scalings
        Scaled_fit_signals = np.array([s * Fit_y for s in Scales])

        Data_signals = np.tile(Data_y, (len(Scalings), 1))
        Data_errors = np.tile(Data_err, (len(Scalings), 1))

        calc = (Data_signals - Scaled_fit_signals) / (Data_errors)
        costs = np.power(calc / (np.sqrt(2) * sigma), 2)
        sums = np.nansum(costs, axis=1)
        loc = np.argmin(sums)
        # maxs = np.nanmax(costs, axis=1)
        # loc = np.argmin(maxs)
        # Cost = maxs[loc]
        Scale = Scales[loc]
        Fit_y = Scale * Fit_y

        return Fit_y

    ## Import data
    ###############################################################
    ##                                                           ##
    ##                        DATA TO INPUT                      ##
    ##                                                           ##
    ###############################################################

    ## Define the shot day, shot number, and diagnostic
    Shot_day = 'OMEGA_Jun2023'
    Shot_number = 108617

    ## If using TDYNO_NLUF Box account, User as required in Parent_loc
    User = 'hpoole'

    ## Bools for what you want to run and if you want to save outputs
    Save_info = False
    Run_CMAES = False
    Run_MCMC = True
    Run_fits = True

    ###############################################################

    ###############################################################
    ##                                                           ##
    ##                      FILE LOCATIONS                       ##
    ##                                                           ##
    ###############################################################
    Global_loc = os.path.join('/', 'Users', User, 'Library', 'CloudStorage', 'Box-Box', 'TDYNO_NLUF', 'OMEGA', Shot_day, 'Data')
    # Global_loc = os.path.join('/', 'Users', User, 'Documents', 'TDYNO', 'OMEGA', Shot_day, 'Data')
    Parent_loc = os.path.join(Global_loc, str(Shot_number), 'IAW')

    Raw_files_loc = os.path.join(Parent_loc, 'Scattering_strips')
    Raw_files = sorted(glob.glob(os.path.join(Raw_files_loc, '*ps.txt')))
    Raw_times = [Raw_file.replace('{}/'.format(Raw_files_loc), '').replace('ps.txt', '') for Raw_file in Raw_files]

    for t in range(len(Raw_times)):
        Shot_time = Raw_times[t]
        Raw_file = os.path.join(Raw_files_loc, Raw_files[t])
        print('\nRunning time {} ns ....'.format(int(Shot_time)*1e-3))
        Save_loc = Raw_files_loc.replace('Scattering_strips', 'Results')


        Run = Fitting(Shot_day, Shot_number, Shot_time, Raw_file)

        if Run_MCMC:
            print('... Running MCMC')
            # construct a different process for each function

            from run import Exploration
            EX = Exploration()
            idata = Run.run_mcmc_model(norm_param_inits=EX.norm_param_inits)
            print(idata.posterior)
            # Plot idata with matplotlib (editable)
            params = EX.param_names
            posterior = idata.posterior
            n_params = len(params)

            # samples_list = [posterior[p].values.reshape(-1) for p in params]
            # values = np.vstack(samples_list).T
            # unnorm_values = np.array([Run.unnormalize(values[i]) for i in range(len(values))])


            n_chains = posterior.sizes['chain']
            ncols = int(n_params)
            nrows = 2
            fig, axs = plt.subplots(nrows, ncols, figsize=(3 * ncols, 3 * nrows))
            for c in range(n_chains):
                samples_list = [posterior[p].values[c].reshape(-1) for p in params]
                values = np.vstack(samples_list).T
                unnorm_values = np.array([Run.unnormalize(values[i]) for i in range(len(values))])
                samples = {params[p]: unnorm_values[:, p] for p in range(n_params)}
                stats = {p: {
                            'median': np.median(samples[p]),
                            'p2.5': np.percentile(samples[p], 2.5),
                            'p97.5': np.percentile(samples[p], 97.5)
                         } for p in params}

                for i, p in enumerate(params):
                    ax0, ax1 = axs[0, i], axs[1, i]
                    # plot a density line (KDE) similar to az.plot_trace's marginal plot
                    try:
                        az.plot_kde(samples[p], ax=ax0)
                    except Exception:
                        # fallback: plot sorted samples against a cumulative/density-like axis
                        vals = np.sort(samples[p])
                        dens_like = np.linspace(0, 1, len(vals))
                        ax0.plot(vals, dens_like, color='C0', alpha=0.7)
                    ax0.axvline(stats[p]['median'], color='C1', label='median')
                    ax0.axvline(stats[p]['p2.5'], color='k', linestyle='--', label='95% CI' if i == 0 else None)
                    ax0.axvline(stats[p]['p97.5'], color='k', linestyle='--')

                    ax1.plot(samples[p], np.arange(len(samples[p])), '-', color='C0', alpha=0.7)

                    # show initial normalized value if present
                    try:
                        for ax in [ax0, ax1]:
                            ax.axvline(EX.param_inits[i], color='C2', linestyle=':', label='init' if i == 0 else None)
                    except Exception:
                        pass

                    
                    ax1.set_xlabel(f'{p} [{EX.param_units[i]}]')
                    ax0.set_ylabel('Frequency')
                    ax1.set_ylabel('Sample')

                    ax0.set_title(p)
                    # if i == 0:
                    #     ax0.legend()
                # remove unused axes
                # for j in range(n_params, len(axs)):
                #     fig.delaxes(axs[j])
                # fig.tight_layout()
            
            plt.show()
            sys.exit()
            
            n_draws = posterior.sizes['draw']

            # dict of numpy arrays shaped (chain, draw) for each parameter
            param_arrays = {p: posterior[p].values for p in params}

            # per-parameter, per-chain lists: samples_by_chain[param] -> [array(chain0), array(chain1), ...]
            samples_by_chain = {p: [param_arrays[p][c].copy() for c in range(n_chains)] for p in params}

            # If you need flattened samples across all chains/draws (as used later), produce samples_list:
            samples_list = [param_arrays[p].reshape(-1) for p in params]
            samples_list = [posterior[p].values.reshape(-1) for p in params]
            values = np.vstack(samples_list).T
            unnorm_values = np.array([Run.unnormalize(values[i]) for i in range(len(values))])

            samples = {params[p]: unnorm_values[:, p] for p in range(n_params)}
            stats = {p: {
                        'median': np.median(samples[p]),
                        'p2.5': np.percentile(samples[p], 2.5),
                        'p97.5': np.percentile(samples[p], 97.5)
                     } for p in params}

            # Parameter histograms (grid)
            ncols = int(n_params)
            nrows = 2
            fig, axs = plt.subplots(nrows, ncols, figsize=(3 * ncols, 5 * nrows))
            for i, p in enumerate(params):
                ax0, ax1 = axs[0, i], axs[1, i]
                ax0.hist(samples[p], bins=40, color='C0', alpha=0.7)
                ax0.axvline(stats[p]['median'], color='C1', label='median')
                ax0.axvline(stats[p]['p2.5'], color='k', linestyle='--', label='95% CI' if i == 0 else None)
                ax0.axvline(stats[p]['p97.5'], color='k', linestyle='--')

                ax1.plot(samples[p], np.arange(len(samples[p])), '-', color='C0', alpha=0.7)

                # show initial normalized value if present
                try:
                    ax0.axvline(EX.norm_param_inits[i], color='C2', linestyle=':', label='init' if i == 0 else None)
                    ax1.axvline(EX.norm_param_inits[i], color='C2', linestyle=':', label='init' if i == 0 else None)
                except Exception:
                    pass
                
                # ax1.plot(samples[p], '-', color='C0', alpha=0.7)
                
                ax0.set_title(p)
                if i == 0:
                    ax0.legend()
            # remove unused axes
            for j in range(n_params, len(axs)):
                fig.delaxes(axs[j])
            fig.tight_layout()

            # Overlay median fit on the experimental data for quick visual check
            medians = [stats[p]['median'] for p in params]
            unnorm_med = Run.unnormalize(medians)   # convert normalized medians -> physical params
            fit_y = Run.generate_fit(unnorm_med)    # generate fit using Fitting.generate_fit

            fig2, ax2 = plt.subplots(figsize=(8, 4))
            ax2.errorbar(Run.raw_lambda, Run.raw_I, yerr=np.abs(Run.raw_err), fmt='o', ms=3, color='0.4', label='data')
            ax2.plot(Run.raw_lambda, fit_y, 'r-', lw=2, label='median fit')
            ax2.set_xlabel('wavelength (nm)')
            ax2.set_ylabel('intensity')
            ax2.legend()
            plt.show()
            sys.exit()